project:
  type: default
  output-dir: _output

format:
  html:
    theme: none
    css: styles/sheet.css
    toc: false
    self-contained: true
  pdf:
    pdf-engine: weasyprint
    css: styles/sheet.css
    toc: false
